name: Arduino CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Arduino Sketch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        with:
          version: '2.0.0'

      - name: Install Seeeduino XIAO core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
          arduino-cli core update-index
          arduino-cli core install Seeeduino:samd


      - name: Install Libraries
        run: |
          arduino-cli lib install "Adafruit_LSM6DSOX" "Adafruit_BMP3XX" "Wire" "SD" "Servo"

      - name: Compile All Sketches
        run: |
          for sketch in $(find . -name '*.ino'); do
            arduino-cli compile --fqbn Seeeduino:samd:seeed_XIAO_m0 "$sketch"
          done

