name: Arduino CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Arduino Sketch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        with:
          version: "1.x"

      - name: Install Seeeduino XIAO core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
          arduino-cli config library --enable-unsafe-install true
          arduino-cli core update-index
          arduino-cli core install Seeeduino:samd


      - name: Install Libraries
        run: |
          arduino-cli lib install --git-url https://github.com/arduino-libraries/Arduino_LSM6DSOX.git
          arduino-cli lib install "Dictionary@3.5.0" "Adafruit_LSM6DSOX@1.1.2" "Adafruit BMP3XX Library@2.1.5"

      - name: Compile All Sketches
        run: |
          for sketch in $(find . -name '*.ino'); do
            arduino-cli compile --fqbn Seeeduino:samd:seeed_XIAO_m0 "$sketch"
          done

