name: Arduino CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Arduino Sketch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        with:
          version: "1.x"

      - name: Install Seeeduino XIAO core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core update-index
          arduino-cli core install Seeeduino:samd


      - name: Install Libraries
        run: |
          arduino-cli lib install --git-url https://github.com/arduino-libraries/Arduino_LSM6DSOX.git https://github.com/adafruit/Adafruit_BMP3XX.git
          arduino-cli lib install "Dictionary@3.5.0"
          arduino-cli lib install "Servo@1.2.2" "SD@1.3.0" "Wire@1.0.5"

      - name: Compile All Sketches
        run: |
          for sketch in $(find . -name '*.ino'); do
            arduino-cli compile --fqbn Seeeduino:samd:seeed_XIAO_m0 "$sketch"
          done

