name: Arduino Compilation Check

on:
  push:
    branches:
      - main
    paths:
      - "datalogger/datalogger.ino"
      - "datalogger2025/datalogger2025.ino"
  pull_request:
    branches:
      - main
    paths:
      - "datalogger/datalogger.ino"
      - "datalogger2025/datalogger2025.ino"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Arduino CLI
      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      # Compile the sketch
      - name: Compile Arduino Sketch
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install arduino:avr # Change this for your board
          arduino-cli compile --fqbn arduino:avr:uno path/to/your/sketch.ino
